using System.Collections.Generic;
using System.Windows.Controls;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathAnimations.Properties
{
    // Type of Shapes
    public enum typeOfShapes
    {
        quadrilateral, // Dörtgen
        square, // Kare
        triangle, // Üçgen
        rectangle, //dikdörtgen
    }
    //Component
    public abstract class shapes
    {
        protected string _name;
        protected typeOfShapes _typeOfShapes;

        protected shapes(string name, typeOfShapes typeOfShapes)
        {
            _name = name;
            _typeOfShapes = typeOfShapes;
        }

        public abstract void AddShapes(shapes _shapes);
        public abstract void RemoveShapes(shapes _shapes);

    }

    //composite
    public class secondGeneration : shapes
    {
        List<shapes> shapes = new List<shapes>();

        public secondGeneration(string name, typeOfShapes typeOfShapes) : base(name, typeOfShapes)
        {

        }

        public override void AddShapes(shapes _shapes)
        {
            shapes.Add(_shapes);
        }

        public override void RemoveShapes(shapes _shapes)
        {
            shapes.Remove(_shapes);
        }

    }

    //leaf
    public class ThirdGeneration : shapes
    {
        public ThirdGeneration(string name, typeOfShapes typeOfShapes) : base(name, typeOfShapes)
        {

        }

        public override void AddShapes(shapes _shapes)
        {
            throw new System.NotImplementedException();
        }

        public override void RemoveShapes(shapes _shapes)
        {
            throw new System.NotImplementedException();
        }
    }



    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]

    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {


        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        public class WorkPoint
        {
            public object GeneralFunction()
            {
                //Composite nesnesi oluşturdu.
                secondGeneration LsecondGeneration_ = new secondGeneration("quadrilateral", typeOfShapes.quadrilateral);
                //Oluşturulan ilk composite nesnesinin Leaf nesneleri oluştruldu.
                LsecondGeneration_.AddShapes(new ThirdGeneration("square", typeOfShapes.square));

                return LsecondGeneration_;
            }

        }


        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
            set
            {
                WorkPoint a = new WorkPoint();
                if (a.GeneralFunction() != null)
                { }
            }
        }



    }

}
